import 'dart:io';
import 'package:edulink_app/core/theme/app_theam.dart';
import 'package:edulink_app/site/features/teacher/services/teacher_subject_service.dart';
import 'package:edulink_app/site/shared_widgets/custom_textField.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';

// ─── Entry-test question model ───────────────────────────────────────────────
class _QuestionDraft {
  final TextEditingController text = TextEditingController();
  final List<_OptionDraft> options = [
    _OptionDraft(), _OptionDraft(), _OptionDraft(), _OptionDraft(),
  ];
  int correctIndex = 0;

  void dispose() {
    text.dispose();
    for (final o in options) o.dispose();
  }
}

class _OptionDraft {
  final TextEditingController text = TextEditingController();
  void dispose() => text.dispose();
}

// ─── Widget ──────────────────────────────────────────────────────────────────
class AddLesson extends StatefulWidget {
  final bool isVisible;
  final VoidCallback onClose;
  final int courseId;

  const AddLesson({
    super.key,
    required this.isVisible,
    required this.onClose,
    required this.courseId,
  });

  @override
  State<AddLesson> createState() => _AddLessonState();
}

class _AddLessonState extends State<AddLesson> {
  final TeacherSubjectService _service = TeacherSubjectService();

  // ── Basic fields ──────────────────────────────────────────────────────────
  final _titleController = TextEditingController();
  final _availabilityController = TextEditingController(text: '14');
  final _maxViewsController = TextEditingController(text: '5');

  // The API's `Files` field is an array, so a lesson can have multiple
  // general attachments — not just one.
  final List<PlatformFile> _attachmentFiles = [];

  // Homework is now a file upload (HomeworkFile is binary on the API),
  // not a text link — so it's a PlatformFile instead of a controller.
  // Unlike Files, the API only accepts a single HomeworkFile.
  PlatformFile? _homeworkFile;

  // ── Entry test ────────────────────────────────────────────────────────────
  bool _hasEntryTest = false;
  bool _isAiMode = false; // false = Manual, true = AI

  // Manual mode
  final List<_QuestionDraft> _questions = [];

  // AI mode
  PlatformFile? _aiContentFile;
  final _numQuestionsController = TextEditingController(text: '5');
  final _passingScoreController = TextEditingController(text: '60');
  final _retakeIntervalController = TextEditingController(text: '24');
  // "Short Answer" removed — there's no backing AI endpoint for it
  // (only /ai/quiz for Multiple Choice and /ai/true-false for True/False
  // exist), so it was never actually generating anything; offering it as
  // a selectable type was misleading.
  Set<String> _selectedQTypes = {'Multiple Choice'};

  // Questions generated by the AI endpoints, normalized to the same shape
  // `addEntryTest` expects: { text, options: [{ text, isCorrect }] }.
  // Cleared whenever the source file / question types / count change so a
  // stale generation can never be silently submitted.
  List<Map<String, dynamic>>? _aiGeneratedQuestions;
  bool _isGeneratingAi = false;
  // Whether the "+ N more" toggle in the AI preview is expanded to show
  // every generated question instead of just the first 5.
  bool _aiPreviewExpanded = false;

  bool _isSaving = false;

  // ─────────────────────────────────────────────────────────────────────────
  @override
  void initState() {
    super.initState();
    _addQuestion(); // start with one blank question in manual mode
    // A changed question count invalidates any previous AI generation —
    // tracked via listener instead of relying on custom_textField exposing
    // onChanged.
    _numQuestionsController.addListener(_invalidateAiGeneration);
  }

  void _invalidateAiGeneration() {
    if (_aiGeneratedQuestions != null) {
      setState(() => _aiGeneratedQuestions = null);
    }
  }

  @override
  void dispose() {
    _titleController.dispose();
    _availabilityController.dispose();
    _maxViewsController.dispose();
    _numQuestionsController.removeListener(_invalidateAiGeneration);
    _numQuestionsController.dispose();
    _passingScoreController.dispose();
    _retakeIntervalController.dispose();
    for (final q in _questions) q.dispose();
    super.dispose();
  }

  void _addQuestion() {
    setState(() => _questions.add(_QuestionDraft()));
  }

  void _removeQuestion(int i) {
    setState(() {
      _questions[i].dispose();
      _questions.removeAt(i);
    });
  }

  // `withData: true` is required so PlatformFile.bytes is populated.
  // On Flutter Web there is no filesystem, so PlatformFile.path is always
  // null and dart:io-based APIs (like Dio's MultipartFile.fromFile) throw
  // "Unsupported operation" if bytes aren't available as a fallback.
  //
  // `allowMultiple: true` lets the teacher attach more than one file at
  // once, matching the API's `Files` field which is an array. Picking
  // again adds to the existing selection rather than replacing it, so
  // multiple picker trips can build up the same attachment list.
  Future<void> _pickAttachmentFiles() async {
    final result = await FilePicker.pickFiles(
      withData: true,
      allowMultiple: true,
    );
    if (result != null && result.files.isNotEmpty) {
      setState(() => _attachmentFiles.addAll(result.files));
    }
  }

  void _removeAttachmentFile(int index) {
    setState(() => _attachmentFiles.removeAt(index));
  }

  // Picks the homework file. `withData: true` so PlatformFile.bytes is
  // populated — needed on Flutter Web where `.path` isn't available, and
  // harmless to keep on mobile/desktop too since homework files are
  // typically small documents (not large videos).
  Future<void> _pickHomeworkFile() async {
    final result = await FilePicker.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['pdf', 'doc', 'docx', 'txt', 'pptx', 'zip'],
      withData: true,
    );
    if (result != null && result.files.isNotEmpty) {
      setState(() => _homeworkFile = result.files.first);
    }
  }

  Future<void> _pickAiContentFile() async {
    final result = await FilePicker.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['pdf'],
      withData: true,
    );
    if (result != null && result.files.isNotEmpty) {
      setState(() {
        _aiContentFile = result.files.first;
        // A new source file invalidates whatever was generated before.
        _aiGeneratedQuestions = null;
      });
    }
  }

  /// Calls the AI generation endpoints (`/ai/quiz` for Multiple Choice and
  /// `/ai/true-false` for True/False — both take the uploaded PDF plus
  /// `numQuestions`) for every selected question type, and stores the
  /// combined, normalized result in [_aiGeneratedQuestions].
  Future<void> _generateAiQuestions() async {
    if (_aiContentFile == null) return;

    setState(() {
      _isGeneratingAi = true;
      _aiGeneratedQuestions = null;
    });

    final numQuestions = int.tryParse(_numQuestionsController.text) ?? 5;
    final results = <Map<String, dynamic>>[];

    try {
      if (_selectedQTypes.contains('Multiple Choice')) {
        final mcq = await _service.generateAiQuestions(
          pdf: _aiContentFile!,
          numQuestions: numQuestions,
          trueFalse: false,
        );
        results.addAll(mcq);
      }

      if (_selectedQTypes.contains('True / False')) {
        final tf = await _service.generateAiQuestions(
          pdf: _aiContentFile!,
          numQuestions: numQuestions,
          trueFalse: true,
        );
        results.addAll(tf);
      }

      if (!mounted) return;

      setState(() {
        _aiGeneratedQuestions = results;
        _aiPreviewExpanded = false;
      });

      if (results.isEmpty) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text(
            'Select at least Multiple Choice or True/False to generate questions.',
          )),
        );
      }
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Failed to generate questions: $e')),
      );
    } finally {
      if (mounted) setState(() => _isGeneratingAi = false);
    }
  }

  Future<void> _saveLesson() async {
    if (_titleController.text.isEmpty) return;
    setState(() => _isSaving = true);
    try {
      // Build entry-test payload if needed — either from the manually
      // typed questions, or from whatever the AI step generated.
      List<Map<String, dynamic>>? questions;
      if (_hasEntryTest && !_isAiMode && _questions.isNotEmpty) {
        questions = _questions.map((q) {
          return {
            'text': q.text.text.trim(),
            'options': List.generate(q.options.length, (i) => {
              'text': q.options[i].text.text.trim(),
              'isCorrect': i == q.correctIndex,
            }),
          };
        }).toList();
      } else if (_hasEntryTest && _isAiMode && _aiGeneratedQuestions != null) {
        questions = _aiGeneratedQuestions;
      }

      final lessonId = await _service.addLesson(
        courseId: widget.courseId,
        title: _titleController.text.trim(),
        attachmentFiles: _attachmentFiles,
        availableDays: int.tryParse(_availabilityController.text) ?? 14,
        maxViews: int.tryParse(_maxViewsController.text) ?? 5,
        homeworkFile: _homeworkFile,
        hasEntryTest: _hasEntryTest,
      );

      if (_hasEntryTest && questions != null && questions.isNotEmpty) {
        await _service.addEntryTest(
          lessonId: lessonId,
          title: _titleController.text.trim(),
          passingScore: int.tryParse(_passingScoreController.text) ?? 60,
          retakeIntervalHours: int.tryParse(_retakeIntervalController.text) ?? 24,
          questions: questions,
        );
      }

      _titleController.clear();
      setState(() {
        _attachmentFiles.clear();
        _homeworkFile = null;
        _hasEntryTest = false;
        _aiContentFile = null;
        _aiGeneratedQuestions = null;
      });
      widget.onClose();
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Failed to save lesson: $e')),
      );
    } finally {
      if (mounted) setState(() => _isSaving = false);
    }
  }

  // ── Build ─────────────────────────────────────────────────────────────────
  @override
  Widget build(BuildContext context) {
    final panelWidth = MediaQuery.of(context).size.width < 600
        ? MediaQuery.of(context).size.width
        : 400.0;

    return AnimatedPositioned(
      duration: const Duration(milliseconds: 280),
      curve: Curves.easeInOut,
      right: widget.isVisible ? 0 : -panelWidth,
      top: 0,
      bottom: 0,
      width: panelWidth,
      child: Material(
        elevation: 12,
        shadowColor: Colors.black.withOpacity(0.15),
        color: Colors.white,
        child: Column(
          children: [
            _buildHeader(),
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(20),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // ── Lesson Title ────────────────────────────────────────
                    _label('Lesson Title *'),
                    const SizedBox(height: 6),
                    custom_textField(
                      controller: _titleController,
                      hintText: 'Enter lesson title',
                    ),
                    const SizedBox(height: 20),

                    // ── Attachment Upload (multiple files) ──────────────────
                    _label('Attachment Upload'),
                    const SizedBox(height: 8),
                    _multiFilePicker(
                      files: _attachmentFiles,
                      onPick: _pickAttachmentFiles,
                      onRemoveAt: _removeAttachmentFile,
                    ),
                    const SizedBox(height: 4),
                    const Text(
                      'Upload one or more files (PDF, video, doc, etc.)',
                      style: TextStyle(
                        fontFamily: 'Inter', fontSize: 11, color: AppColors.slate400,
                      ),
                    ),
                    const SizedBox(height: 20),

                    // ── Availability & Max Views ────────────────────────────
                    Row(children: [
                      Expanded(child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          _label('Availability (days)'),
                          const SizedBox(height: 6),
                          custom_textField(controller: _availabilityController),
                        ],
                      )),
                      const SizedBox(width: 12),
                      Expanded(child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          _label('Max Views'),
                          const SizedBox(height: 6),
                          custom_textField(controller: _maxViewsController),
                        ],
                      )),
                    ]),
                    const SizedBox(height: 20),

                    // ── Homework File ───────────────────────────────────────
                    _label('Homework File'),
                    const SizedBox(height: 8),
                    _filePicker(
                      file: _homeworkFile,
                      onPick: _pickHomeworkFile,
                      onClear: () => setState(() => _homeworkFile = null),
                    ),
                    const SizedBox(height: 4),
                    const Text(
                      'Upload the homework document (PDF, DOC, DOCX, TXT, PPTX, ZIP)',
                      style: TextStyle(
                        fontFamily: 'Inter', fontSize: 11, color: AppColors.slate400,
                      ),
                    ),
                    const SizedBox(height: 20),

                    // ── Enable Entry Test toggle ────────────────────────────
                    _entryTestToggle(),

                    // ── Entry Test expanded section ─────────────────────────
                    AnimatedSize(
                      duration: const Duration(milliseconds: 250),
                      curve: Curves.easeInOut,
                      child: _hasEntryTest
                          ? _buildEntryTestSection()
                          : const SizedBox.shrink(),
                    ),

                    const SizedBox(height: 28),

                    // ── Save button ─────────────────────────────────────────
                    SizedBox(
                      width: double.infinity,
                      child: ElevatedButton(
                        style: ElevatedButton.styleFrom(
                          backgroundColor: AppColors.primary,
                          padding: const EdgeInsets.symmetric(vertical: 14),
                          shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(8)),
                        ),
                        onPressed: _isSaving ? null : _saveLesson,
                        child: _isSaving
                            ? const SizedBox(
                                width: 18, height: 18,
                                child: CircularProgressIndicator(
                                    color: Colors.white, strokeWidth: 2))
                            : const Text(
                                'Save Lesson',
                                style: TextStyle(
                                  fontFamily: 'Inter',
                                  fontSize: 14,
                                  fontWeight: FontWeight.w600,
                                  color: Colors.white,
                                ),
                              ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  // ── Sub-builders ───────────────────────────────────────────────────────────

  Widget _buildHeader() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
      decoration: const BoxDecoration(
        border: Border(bottom: BorderSide(color: AppColors.slate200)),
      ),
      child: Row(
        children: [
          const Text(
            'Add Lesson',
            style: TextStyle(
              fontFamily: 'Inter',
              fontSize: 15,
              fontWeight: FontWeight.w600,
              color: AppColors.slate800,
            ),
          ),
          const Spacer(),
          IconButton(
            icon: const Icon(Icons.close_rounded, color: AppColors.slate500),
            onPressed: widget.onClose,
            padding: EdgeInsets.zero,
            constraints: const BoxConstraints(),
          ),
        ],
      ),
    );
  }

  /// Single-file picker — still used for Homework (the API only accepts
  /// one HomeworkFile).
  Widget _filePicker({
    required PlatformFile? file,
    required VoidCallback onPick,
    required VoidCallback onClear,
  }) {
    return Row(
      children: [
        OutlinedButton.icon(
          onPressed: onPick,
          icon: const Icon(Icons.upload_rounded, size: 16),
          label: const Text('Choose File'),
          style: OutlinedButton.styleFrom(
            foregroundColor: AppColors.slate700,
            side: const BorderSide(color: AppColors.slate300),
            textStyle: const TextStyle(fontFamily: 'Inter', fontSize: 13),
            padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(6)),
          ),
        ),
        const SizedBox(width: 10),
        Expanded(
          child: file == null
              ? const Text(
                  'No file chosen',
                  style: TextStyle(
                    fontFamily: 'Inter', fontSize: 13, color: AppColors.slate400,
                  ),
                )
              : Row(
                  children: [
                    Expanded(
                      child: Text(
                        file.name,
                        overflow: TextOverflow.ellipsis,
                        style: const TextStyle(
                          fontFamily: 'Inter', fontSize: 13, color: AppColors.slate700,
                        ),
                      ),
                    ),
                    GestureDetector(
                      onTap: onClear,
                      child: const Icon(Icons.close_rounded,
                          size: 16, color: AppColors.slate400),
                    ),
                  ],
                ),
        ),
      ],
    );
  }

  /// Multi-file picker — used for the `Files` attachments field. Shows a
  /// "Choose Files" button plus a chip-style list of everything picked so
  /// far, each individually removable, instead of only ever holding one
  /// file at a time.
  Widget _multiFilePicker({
    required List<PlatformFile> files,
    required VoidCallback onPick,
    required void Function(int) onRemoveAt,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            OutlinedButton.icon(
              onPressed: onPick,
              icon: const Icon(Icons.upload_rounded, size: 16),
              label: const Text('Choose Files'),
              style: OutlinedButton.styleFrom(
                foregroundColor: AppColors.slate700,
                side: const BorderSide(color: AppColors.slate300),
                textStyle: const TextStyle(fontFamily: 'Inter', fontSize: 13),
                padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(6)),
              ),
            ),
            const SizedBox(width: 10),
            if (files.isEmpty)
              const Expanded(
                child: Text(
                  'No files chosen',
                  style: TextStyle(
                    fontFamily: 'Inter', fontSize: 13, color: AppColors.slate400,
                  ),
                ),
              )
            else
              Text(
                '${files.length} file${files.length == 1 ? '' : 's'} selected',
                style: const TextStyle(
                  fontFamily: 'Inter', fontSize: 12, color: AppColors.slate500,
                ),
              ),
          ],
        ),
        if (files.isNotEmpty) ...[
          const SizedBox(height: 10),
          Column(
            children: List.generate(files.length, (i) {
              final file = files[i];
              return Container(
                margin: const EdgeInsets.only(bottom: 6),
                padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 8),
                decoration: BoxDecoration(
                  color: AppColors.slate50,
                  borderRadius: BorderRadius.circular(6),
                  border: Border.all(color: AppColors.slate200),
                ),
                child: Row(
                  children: [
                    const Icon(Icons.insert_drive_file_outlined,
                        size: 16, color: AppColors.slate400),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        file.name,
                        overflow: TextOverflow.ellipsis,
                        style: const TextStyle(
                          fontFamily: 'Inter', fontSize: 13, color: AppColors.slate700,
                        ),
                      ),
                    ),
                    GestureDetector(
                      onTap: () => onRemoveAt(i),
                      child: const Padding(
                        padding: EdgeInsets.all(2),
                        child: Icon(Icons.close_rounded,
                            size: 16, color: AppColors.slate400),
                      ),
                    ),
                  ],
                ),
              );
            }),
          ),
        ],
      ],
    );
  }

  Widget _entryTestToggle() {
    return GestureDetector(
      onTap: () => setState(() => _hasEntryTest = !_hasEntryTest),
      child: Row(children: [
        AnimatedContainer(
          duration: const Duration(milliseconds: 150),
          width: 20,
          height: 20,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(4),
            color: _hasEntryTest ? AppColors.primary : Colors.white,
            border: Border.all(
              color: _hasEntryTest ? AppColors.primary : AppColors.slate300,
              width: 1.5,
            ),
          ),
          child: _hasEntryTest
              ? const Icon(Icons.check, size: 14, color: Colors.white)
              : null,
        ),
        const SizedBox(width: 10),
        const Text(
          'Enable Entry Test',
          style: TextStyle(
            fontFamily: 'Inter', fontSize: 13, color: AppColors.slate700,
          ),
        ),
      ]),
    );
  }

  Widget _buildEntryTestSection() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const SizedBox(height: 16),

        // ── Manual / AI tab switcher ──────────────────────────────────────
        Container(
          decoration: BoxDecoration(
            color: AppColors.slate100,
            borderRadius: BorderRadius.circular(8),
          ),
          padding: const EdgeInsets.all(4),
          child: Row(children: [
            _modeTab(label: '✏️  Create Manually', selected: !_isAiMode,
                onTap: () => setState(() => _isAiMode = false)),
            _modeTab(label: '✨  Create with AI', selected: _isAiMode,
                onTap: () => setState(() => _isAiMode = true)),
          ]),
        ),
        const SizedBox(height: 16),

        // ── Mode body ─────────────────────────────────────────────────────
        _isAiMode ? _buildAiMode() : _buildManualMode(),

        // ── Passing score & retake interval (shared) ──────────────────────
        const SizedBox(height: 16),
        Row(children: [
          Expanded(child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _label('Passing Score %'),
              const SizedBox(height: 6),
              custom_textField(controller: _passingScoreController),
            ],
          )),
          const SizedBox(width: 12),
          Expanded(child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _label('Retake Interval (hrs)'),
              const SizedBox(height: 6),
              custom_textField(controller: _retakeIntervalController),
            ],
          )),
        ]),
      ],
    );
  }

  Widget _modeTab({
    required String label,
    required bool selected,
    required VoidCallback onTap,
  }) {
    return Expanded(
      child: GestureDetector(
        onTap: onTap,
        child: AnimatedContainer(
          duration: const Duration(milliseconds: 150),
          padding: const EdgeInsets.symmetric(vertical: 8),
          decoration: BoxDecoration(
            color: selected ? Colors.white : Colors.transparent,
            borderRadius: BorderRadius.circular(6),
            boxShadow: selected
                ? [BoxShadow(color: Colors.black.withOpacity(0.08),
                    blurRadius: 4, offset: const Offset(0, 1))]
                : [],
          ),
          child: Text(
            label,
            textAlign: TextAlign.center,
            style: TextStyle(
              fontFamily: 'Inter',
              fontSize: 13,
              fontWeight: selected ? FontWeight.w600 : FontWeight.w400,
              color: selected ? AppColors.primary : AppColors.slate500,
            ),
          ),
        ),
      ),
    );
  }

  // ── Manual Mode ────────────────────────────────────────────────────────────
  Widget _buildManualMode() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            _label('Test Questions'),
            TextButton.icon(
              onPressed: _addQuestion,
              icon: const Icon(Icons.add_rounded, size: 16, color: AppColors.primary),
              label: const Text(
                'Add Question',
                style: TextStyle(
                  fontFamily: 'Inter', fontSize: 13, color: AppColors.primary,
                ),
              ),
              style: TextButton.styleFrom(padding: EdgeInsets.zero),
            ),
          ],
        ),
        const SizedBox(height: 8),
        ..._questions.asMap().entries.map((e) => _buildQuestionCard(e.key, e.value)),
      ],
    );
  }

  Widget _buildQuestionCard(int index, _QuestionDraft q) {
    return Container(
      margin: const EdgeInsets.only(bottom: 16),
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        border: Border.all(color: AppColors.slate200),
        borderRadius: BorderRadius.circular(8),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Question header
          Row(
            children: [
              Text(
                'Question ${index + 1}',
                style: const TextStyle(
                  fontFamily: 'Inter', fontSize: 13,
                  fontWeight: FontWeight.w600, color: AppColors.slate700,
                ),
              ),
              const Spacer(),
              // Question Type dropdown (only Multiple Choice for now)
              const Text(
                'Multiple Choice',
                style: TextStyle(
                  fontFamily: 'Inter', fontSize: 12, color: AppColors.slate500,
                ),
              ),
              if (_questions.length > 1) ...[
                const SizedBox(width: 8),
                GestureDetector(
                  onTap: () => _removeQuestion(index),
                  child: const Icon(Icons.delete_outline_rounded,
                      size: 18, color: AppColors.slate400),
                ),
              ],
            ],
          ),
          const SizedBox(height: 10),

          // Question text
          const Text(
            'Question Text *',
            style: TextStyle(
              fontFamily: 'Inter', fontSize: 12,
              fontWeight: FontWeight.w500, color: AppColors.slate600,
            ),
          ),
          const SizedBox(height: 5),
          custom_textField(
            controller: q.text,
            hintText: 'Enter question...',
          ),
          const SizedBox(height: 12),

          // Answer options
          const Text(
            'Answer Options',
            style: TextStyle(
              fontFamily: 'Inter', fontSize: 12,
              fontWeight: FontWeight.w500, color: AppColors.slate600,
            ),
          ),
          const SizedBox(height: 6),
          ...List.generate(q.options.length, (i) => _buildOptionRow(q, i)),
          const SizedBox(height: 4),
          const Text(
            'Select the radio button next to the correct answer.',
            style: TextStyle(
              fontFamily: 'Inter', fontSize: 11, color: AppColors.slate400,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildOptionRow(_QuestionDraft q, int i) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: Row(
        children: [
          GestureDetector(
            onTap: () => setState(() => q.correctIndex = i),
            child: Container(
              width: 18, height: 18,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                border: Border.all(
                  color: q.correctIndex == i
                      ? AppColors.primary : AppColors.slate300,
                  width: 2,
                ),
              ),
              child: q.correctIndex == i
                  ? Center(
                      child: Container(
                        width: 8, height: 8,
                        decoration: const BoxDecoration(
                          shape: BoxShape.circle,
                          color: AppColors.primary,
                        ),
                      ),
                    )
                  : null,
            ),
          ),
          const SizedBox(width: 8),
          Expanded(
            child: custom_textField(
              controller: q.options[i].text,
              hintText: 'Option ${i + 1}',
            ),
          ),
        ],
      ),
    );
  }

  // ── AI Mode ────────────────────────────────────────────────────────────────
  Widget _buildAiMode() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        // Upload lesson content
        _label('Upload Lesson Content *'),
        const SizedBox(height: 8),
        _filePicker(
          file: _aiContentFile,
          onPick: _pickAiContentFile,
          onClear: () => setState(() {
            _aiContentFile = null;
            _aiGeneratedQuestions = null;
          }),
        ),
        const SizedBox(height: 4),
        const Text(
          'PDF only — AI will analyze the content to generate questions.',
          style: TextStyle(
            fontFamily: 'Inter', fontSize: 11, color: AppColors.slate400,
          ),
        ),
        const SizedBox(height: 16),

        // Question types
        // "Short Answer" removed — no AI endpoint backs it, only
        // Multiple Choice (/ai/quiz) and True/False (/ai/true-false) exist.
        _label('Question Types *'),
        const SizedBox(height: 8),
        Wrap(
          spacing: 8,
          children: ['Multiple Choice', 'True / False']
              .map((type) {
            final selected = _selectedQTypes.contains(type);
            return GestureDetector(
              onTap: () => setState(() {
                if (selected && _selectedQTypes.length > 1) {
                  _selectedQTypes.remove(type);
                } else {
                  _selectedQTypes.add(type);
                }
                // Question-type changes invalidate any previous generation.
                _aiGeneratedQuestions = null;
              }),
              child: AnimatedContainer(
                duration: const Duration(milliseconds: 150),
                padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
                decoration: BoxDecoration(
                  color: selected ? AppColors.primary : Colors.white,
                  border: Border.all(
                    color: selected ? AppColors.primary : AppColors.slate300,
                  ),
                  borderRadius: BorderRadius.circular(20),
                ),
                child: Text(
                  type,
                  style: TextStyle(
                    fontFamily: 'Inter',
                    fontSize: 13,
                    color: selected ? Colors.white : AppColors.slate600,
                  ),
                ),
              ),
            );
          }).toList(),
        ),
        const SizedBox(height: 16),

        // Number of questions
        _label('Number of Questions'),
        const SizedBox(height: 6),
        custom_textField(controller: _numQuestionsController),
        const SizedBox(height: 16),

        // Generate button
        SizedBox(
          width: double.infinity,
          child: ElevatedButton.icon(
            style: ElevatedButton.styleFrom(
              backgroundColor: AppColors.primary,
              padding: const EdgeInsets.symmetric(vertical: 13),
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(8)),
            ),
            onPressed: (_aiContentFile == null || _isGeneratingAi)
                ? null
                : _generateAiQuestions,
            icon: _isGeneratingAi
                ? const SizedBox(
                    width: 16, height: 16,
                    child: CircularProgressIndicator(
                        color: Colors.white, strokeWidth: 2),
                  )
                : const Icon(Icons.auto_awesome_rounded,
                    size: 16, color: Colors.white),
            label: Text(
              _isGeneratingAi ? 'Generating...' : 'Generate Test with AI',
              style: const TextStyle(
                fontFamily: 'Inter',
                fontSize: 14,
                fontWeight: FontWeight.w600,
                color: Colors.white,
              ),
            ),
          ),
        ),

        // ── Generated-questions preview ─────────────────────────────────
        if (_aiGeneratedQuestions != null) ...[
          const SizedBox(height: 16),
          _buildAiPreview(),
        ],
      ],
    );
  }

  Widget _buildAiPreview() {
    final questions = _aiGeneratedQuestions!;
    if (questions.isEmpty) {
      return const SizedBox.shrink();
    }

    final visibleCount =
        _aiPreviewExpanded ? questions.length : (questions.length > 5 ? 5 : questions.length);
    final hiddenCount = questions.length - visibleCount;

    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: AppColors.successBg,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: AppColors.success.withOpacity(0.3)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(children: [
            const Icon(Icons.check_circle_outline_rounded, color: AppColors.success, size: 18),
            const SizedBox(width: 8),
            Expanded(
              child: Text(
                'Generated ${questions.length} question${questions.length == 1 ? '' : 's'} — they will be added to this lesson\'s entry test.',
                style: const TextStyle(
                  fontFamily: 'Inter', fontSize: 12, color: AppColors.success,
                ),
              ),
            ),
          ]),
          const SizedBox(height: 12),
          ...questions.take(visibleCount).toList().asMap().entries.map((entry) {
            final i = entry.key;
            final q = entry.value;
            return Padding(
              padding: const EdgeInsets.only(bottom: 12),
              child: _AiQuestionPreviewCard(index: i, question: q),
            );
          }),
          if (questions.length > 5)
            GestureDetector(
              onTap: () => setState(() => _aiPreviewExpanded = !_aiPreviewExpanded),
              child: Padding(
                padding: const EdgeInsets.only(top: 2, bottom: 4),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Text(
                      _aiPreviewExpanded ? 'Show less' : '+ $hiddenCount more',
                      style: const TextStyle(
                        fontFamily: 'Inter',
                        fontSize: 12,
                        fontWeight: FontWeight.w600,
                        color: AppColors.success,
                      ),
                    ),
                    const SizedBox(width: 4),
                    Icon(
                      _aiPreviewExpanded
                          ? Icons.keyboard_arrow_up_rounded
                          : Icons.keyboard_arrow_down_rounded,
                      size: 16,
                      color: AppColors.success,
                    ),
                  ],
                ),
              ),
            ),
        ],
      ),
    );
  }

  // ── Helpers ────────────────────────────────────────────────────────────────
  Widget _label(String text) => Text(
        text,
        style: const TextStyle(
          fontFamily: 'Inter',
          fontSize: 13,
          fontWeight: FontWeight.w500,
          color: AppColors.slate700,
        ),
      );
}

/// Shows one generated question's text plus its full options, with the
/// correct option highlighted — previously the preview only showed the
/// question text, with no way to check the options or which one the AI
/// marked as correct before saving the lesson.
class _AiQuestionPreviewCard extends StatelessWidget {
  final int index;
  final Map<String, dynamic> question;

  const _AiQuestionPreviewCard({required this.index, required this.question});

  @override
  Widget build(BuildContext context) {
    final text = (question['text'] ?? '').toString();
    final options = (question['options'] as List? ?? [])
        .map((o) => Map<String, dynamic>.from(o as Map))
        .toList();

    return Container(
      padding: const EdgeInsets.all(10),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: AppColors.success.withOpacity(0.25)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            '${index + 1}. $text',
            style: const TextStyle(
              fontFamily: 'Inter', fontSize: 12, fontWeight: FontWeight.w600,
              color: AppColors.slate800,
            ),
          ),
          if (options.isNotEmpty) ...[
            const SizedBox(height: 6),
            ...options.map((o) {
              final optText = (o['text'] ?? '').toString();
              final isCorrect = o['isCorrect'] == true;
              return Padding(
                padding: const EdgeInsets.only(top: 3),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Icon(
                      isCorrect
                          ? Icons.check_circle_rounded
                          : Icons.circle_outlined,
                      size: 14,
                      color: isCorrect ? AppColors.success : AppColors.slate400,
                    ),
                    const SizedBox(width: 6),
                    Expanded(
                      child: Text(
                        optText,
                        style: TextStyle(
                          fontFamily: 'Inter',
                          fontSize: 12,
                          color: isCorrect ? AppColors.success : AppColors.slate600,
                          fontWeight: isCorrect ? FontWeight.w600 : FontWeight.w400,
                        ),
                      ),
                    ),
                  ],
                ),
              );
            }),
          ],
        ],
      ),
    );
  }
}